# “Git push -f” или после нас хоть потоп

# 0. Где мы сейчас?
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Jupyter_logo.svg/1200px-Jupyter_logo.svg.png" width="150">

[Jupyter Notebook](https://jupyter.org/) - интерактивная среда для запуска программного кода в браузере. Удобный инструмент для анализа данных, который используется многими специалистами по data science. Позволяет выполнять отдельные ячейки с кодом, а не всю программу сразу, что очень удобно при знакомстве с данными.

# 1. Python
> Python - это свободный интерпретируемый объектно-ориентированный расширяемый встраиваемый язык программирования очень высокого уровня

>*(Г.Россум, Ф.Л.Дж.Дрейк, Д.С.Откидач "Язык программирования Python").*

А если без цитат, то питон - это просто очень крутой язык, созданный в 1991 году [Великодушным пожизненным диктатором](https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D0%BB%D0%B8%D0%BA%D0%BE%D0%B4%D1%83%D1%88%D0%BD%D1%8B%D0%B9_%D0%BF%D0%BE%D0%B6%D0%B8%D0%B7%D0%BD%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D0%B4%D0%B8%D0%BA%D1%82%D0%B0%D1%82%D0%BE%D1%80) Гвидо ван Россумом и названный в честь любимого им шоу [Monty Python's Flying Circus](https://en.wikipedia.org/wiki/Monty_Python%27s_Flying_Circus)

<img src="https://advancelocal-adapter-image-uploads.s3.amazonaws.com/image.oregonlive.com/home/olive-media/width2048/img/tv/photo/2018/10/10/montycastjpg-7ef393e2355a42aa.jpg" width="300">

# 2. Anaconda

[Сборка Anaconda](https://www.anaconda.com/products/individual) включает очень много полезных библиотек для анализа данных.

Среди наиболее популярных библиотек:
 - <a href="http://numpy.org">Numpy</a> - это один из основных пакетов для математических вычислений. Он содержит средства для работы с многомерными массивами и высокоуровневыми математическими функциями
 - <a href="https://www.scipy.org/">SciPy</a> - научные вычисления. Методы оптимизации, интегрирования, модули обработки сигналов и изображений, статистика, линейная алгебра, сплайны, кластеризация и многое другое
 -  <a href="http://pandas.pydata.org/">Pandas</a> - основная библиотека для обработки и анализа данных. Предназначена для данных разной природы - матричных, панельных данных, временных рядов. Претендует на звание самого мощного и гибкого средства для анализа данных с открытым исходным кодом
 - <a href="http://scikit-learn.org/stable/">Scikit-learn</a> - реализация очень многих методов машинного обучения с отличной документацией.
 - <a href="http://http://matplotlib.org/">matplotlib</a> - хорошая библиотека для визуализации данных

 С этими библиотеками вы будете знакомится дальше на курсе, а пока давайте попрактикуемся в решении базовых задач на  чистом Python.

# 3. Задачки

## Задача 1
$N$ хоббитов делят $K$ кусков эльфийского хлеба поровну, не делящийся нацело остаток остается в корзинке у Сэма. Напишите функцию, которая принимает на вход параметры $N$ и $K$ и возвращает два числа: $x$ - cколько кусков эльфиского хлеба достанется каждому хоббиту, и $y$ - сколько кусков остаётся в корзинке.

In [16]:
from PySide6.examples.widgets.itemviews.basicfiltermodel.basicsortfiltermodel import add_mail


def share_bread(N, K):
    # your code here
    if N < 1:
        return f"There are no hobbits"
    if N > K:
        return f"Not enough {K} bread for {N} hobbits: {N - K} pieces left"
    x = K // N  # floor division
    y = K % N  # module
    return x, y


# если в функции всё верно, то после выполнения этой строчки, не должно выскакивать ошибок
assert share_bread(N=0, K=0) == "There are no hobbits"
assert share_bread(N=1, K=0) == "Not enough 0 bread for 1 hobbits: 1 pieces left"
assert share_bread(N=3, K=14) == (4, 2)

## Задача 2

В копях Мории хоббиты нашли стену, на которой высечены разные натуральные числа. Согласно древним сказаниям, это даты сражений. Хоббиты знают, что сражения происходили только по високосным годам. Помогите хоббитам определить, является ли год с данным числом датой великого сражения. Если это так, то верните строку "YOU SHALL PASS", иначе верните "YOU SHALL NOT PASS". Напомним, что в соответствии с хоббитским календарем, год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.

In [14]:
def leap_year(year):
    # your code here
    if not isinstance(year, int) or year < 1:
        return f"Year must be positive integer"

    text_result = "YOU SHALL NOT PASS"
    if year % 4 == 0 and year % 100 != 0 or year % 400 == 0:
        text_result = "YOU SHALL PASS"

    return text_result


assert leap_year(25.4) == 'Year must be positive integer'
assert leap_year(-1) == 'Year must be positive integer'
assert leap_year(5) == 'YOU SHALL NOT PASS'
assert leap_year(8) == 'YOU SHALL PASS'
assert leap_year(200) == 'YOU SHALL NOT PASS'
assert leap_year(400) == 'YOU SHALL PASS'
assert leap_year(800) == 'YOU SHALL PASS'

## Задача 3
<img src="http://i0.kym-cdn.com/photos/images/original/001/187/255/5e9.gif" width=300>


Для могущественного магического ритуала Гендальфу необходимо быстро подсчитывать площадь своего амулета, который умеет менять размеры. Известно, что амулет имеет форму треугольника и Гендальф знает длину каждой из сторон. Напишите функцию, которая считает площадь амулета по трем сторонам.  

**Подсказка:** используйте формулу Герона
$$ S = \sqrt{p(p-a)(p-b)(p-c)} $$
$$ p = \frac{a + b + c}{2}$$


In [22]:
def amulet_area(a, b, c):
    # your code here
    if a <= 0 or b <= 0 or c < 1 or a + b <= c or a + c <= b or b + c <= a:
        return f"Invalid triangle with sides a = {a}, b = {b}, c = {c}."

    p = (a + b + c) / 2
    S = (p * (p - a) * (p - b) * (p - c)) ** 0.5
    return S


assert amulet_area(0, 4, 5) == "Invalid triangle with sides a = 0, b = 4, c = 5."
assert amulet_area(0, -33, 5) == "Invalid triangle with sides a = 0, b = -33, c = 5."
assert amulet_area(0, 4, 0) == "Invalid triangle with sides a = 0, b = 4, c = 0."
assert amulet_area(3, 4, 5) == 6

## Задача 4

Хоббиты собираются пешком идти до Мордора и им нужно подсчитать расстояние, которое им предстоит пройти. Хоббиты смогли вспомнить сразу несколько метрик расстояния: евклидово, манхэттена и косинусное, так что ваша задача - написать функцию под каждую из них. Важное условие - используйте только базовые функции для решения.


* Евклидово расстояние
$$ d(a, b) = \sqrt{\sum_i (a_i - b_i)^2} $$
* Расстояние Манхэттена
$$ d(a, b) = \sum_i |a_i - b_i| $$
* Косинусное расстояние
$$ d(a, b) = 1 - \frac{a^\top b}{||a||_2\cdot||b||_2}$$

In [84]:
def cal_euclidean(a, b):
    ## Your code here
    if len(a) == 0 or len(b) == 0:
        return f"Invalid vectors with lengths {len(a)} and {len(b)}."
    distance = 0
    for i in range(len(a)):
        distance += (a[i] - b[i]) ** 2
    return distance ** 0.5


def cal_manhattan(a, b):
    ## Your code here
    if len(a) == 0 or len(b) == 0:
        return f"Invalid vectors with lengths {len(a)} and {len(b)}."
    distance = 0
    for i in range(len(a)):
        distance += abs(a[i] - b[i])
    return distance

 #realization with only basic functions
def cal_cosine(a, b):
    ## Your code here
    if len(a) == 0 or len(b) == 0:
        return f"Invalid vectors with lengths {len(a)} and {len(b)}."
    ab_mult = 0
    a_magnitude = 0
    b_magnitude = 0
    for i in range(len(a)):
        ab_mult += a[i] * b[i]
        a_magnitude += a[i] ** 2
        b_magnitude += b[i] ** 2
    distance_similarity = ab_mult / (a_magnitude ** 0.5 * b_magnitude ** 0.5)
    return 1 - distance_similarity

In [86]:
import numpy as np

# debugging data
# a = [2,4]
# b = [4,2]

a = np.random.randint(-10, 10, size=10)
b = np.random.randint(-10, 10, size=10)
print(f"a: {a}")
print(f"b: {b}")
print(f"Euclidean distance: {cal_euclidean(a, b)}")
print(f"Manhattan distance: {cal_manhattan(a, b)}")
print(f"Cosine distance: {cal_cosine(a, b)}")

############################################
# Test Cosine distance with np.linalg.norm #
############################################
# Define the vectors
A = np.array(a)
B = np.array(b)
# Calculate cosine similarity
cos_similarity = np.dot(A, B) / (np.linalg.norm(A) * np.linalg.norm(B))
# Calculate cosine distance
cos_distance = 1 - cos_similarity
print("Test Cosine distance with np.linalg.norm: {:.2f}".format(cos_distance))


a: [2, 4]
b: [4, 2]
Euclidean distance: 2.8284271247461903
Manhattan distance: 4
Cosine distance: 0.20000000000000018
Test Cosine distance with np.linalg.norm: 0.20


## Задача 5* (бонусное неоцениваемое задание)

**Замечание:** Поскольку библиотеку numpy мы будем подробно разбирать дальше, то это задание является бонусным, его выполнение необязательно для сдачи ДЗ и не влияет на итоговый балл. Как вариант, можете вернуться к нему после прохождения numpy ;)



Создайте случайный array (`np.random.rand()`) длинной 100. Преобразуйте его так, чтобы
* Максимальный элемент(ы) был равен 1
* Минимальный элемент(ы) был равен 0
* Остальные элементы в интервале от 0 до 1 остаются прежними

In [59]:
my_array = np.random.rand(50, 50)
print(np.max(my_array), np.min(my_array))
print(my_array)

0.9998722692535442 6.971222848639602e-05
[[0.69685757 0.14026378 0.15874987 ... 0.9260508  0.43239756 0.56646392]
 [0.26239136 0.31295947 0.84662903 ... 0.7278186  0.55569243 0.2559744 ]
 [0.2519605  0.66016487 0.79950557 ... 0.59145946 0.16799056 0.34498625]
 ...
 [0.25003343 0.95143355 0.42552425 ... 0.12071982 0.94806369 0.03426853]
 [0.72809735 0.4664035  0.34528602 ... 0.75277817 0.52280201 0.78490264]
 [0.59095819 0.94592698 0.21260893 ... 0.4920016  0.58391839 0.69508378]]


Создайте array размером $5 \times 6$ с целыми числами в интервале [0,50]. Напечатайте колонку, которая содержит максимальный элемент полученной матрицы

In [66]:
my_array = np.random.randint(0, 50, size=(5, 6))  ## Your code here
selected_column = []  ## Your code here
selected_column_index = 0
max_element = 0
for i in my_array:
    if max(i) > max_element:
        for j in range(6):
            if i[j] == max_element:
                selected_column_index = j
                break
for i in my_array:
    selected_column.append(i[selected_column_index])
print('Shape: ', my_array.shape)
print('Array')
print(my_array)
print(f"Selected column: {selected_column}")

Shape:  (5, 6)
Array
[[12 30 33 14 19 19]
 [ 1 36  0 29  6 22]
 [13  9 49 10 28 41]
 [ 6  9  6  1 27 31]
 [23 26 25  5 38 21]]
Selected column: [33, 0, 49, 6, 25]


Напишите функцию, которая принимает на вход матрицу (array) X и возвращает все её уникальные строки в виде новой матрицы.

In [67]:
def get_unique_rows(X):
    # Your code here
    return np.unique(X, axis=0)

In [68]:
X = np.random.randint(4, 6, size=(10, 3))
print(X)

[[5 4 4]
 [5 4 5]
 [5 5 4]
 [5 5 4]
 [5 5 4]
 [5 5 4]
 [5 4 5]
 [5 5 5]
 [5 5 4]
 [4 4 5]]


In [70]:
print(f"Unique matrix: \n {get_unique_rows(X)}")

Unique matrix: 
 [[4 4 5]
 [5 4 4]
 [5 4 5]
 [5 5 4]
 [5 5 5]]
